{
  "formatVersion": "1.1",
  "component": {
    "url": "../../graph-meta/2.0/graph-meta-2.0.module",
    "group": "ru.landgrafhomyak.itmo.web",
    "module": "graph-meta",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "frontendApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-frontend-2.0.klib",
          "url": "graph-meta-frontend-2.0.klib",
          "size": 31051,
          "sha512": "4dd5f46355521773798305f4af673ae4dbaac460c7a5e7def47a8612d9fb6991b3f5069f0264a8833a24a6233fa0574d4af06ed3aafea6d0d3324979ac5cbaf7",
          "sha256": "3fd477a94767daebfb5d1fdcc894f0d0b20cffa2894cfeeec8aa63ef11905402",
          "sha1": "a07ede17fd2b31efb2754fbaadbbbde117bcd0f7",
          "md5": "aa7d81060098723945a495ee7f7fb273"
        }
      ]
    },
    {
      "name": "frontendRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-frontend-2.0.klib",
          "url": "graph-meta-frontend-2.0.klib",
          "size": 31051,
          "sha512": "4dd5f46355521773798305f4af673ae4dbaac460c7a5e7def47a8612d9fb6991b3f5069f0264a8833a24a6233fa0574d4af06ed3aafea6d0d3324979ac5cbaf7",
          "sha256": "3fd477a94767daebfb5d1fdcc894f0d0b20cffa2894cfeeec8aa63ef11905402",
          "sha1": "a07ede17fd2b31efb2754fbaadbbbde117bcd0f7",
          "md5": "aa7d81060098723945a495ee7f7fb273"
        }
      ]
    },
    {
      "name": "frontendSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lib-frontend-2.0-sources.jar",
          "url": "graph-meta-frontend-2.0-sources.jar",
          "size": 5761,
          "sha512": "5c9831d2f37a82f78fbca0918cf493948619106116186ff8cb1adf9b2072ded1b3fdcaa33ef48ab7f44682c4a4d089487aea7c32debbaf68df15519cdb893a57",
          "sha256": "f8867d816e9afbb7eb2adf94c8e77a2cb681ca25cb0f06c5c932faf1b106c5db",
          "sha1": "6642712175484bdc64a7910c96f4a7715316b906",
          "md5": "c2a4606223e4550a36fb0e44cea40499"
        }
      ]
    }
  ]
}
