{
  "formatVersion": "1.1",
  "component": {
    "url": "../../graph-meta/2.2/graph-meta-2.2.module",
    "group": "ru.landgrafhomyak.itmo.web",
    "module": "graph-meta",
    "version": "2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "frontendApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-frontend-2.2.klib",
          "url": "graph-meta-frontend-2.2.klib",
          "size": 31045,
          "sha512": "ec1bfc65f5d52f44e34fd94e8896f58a734deeae55375184ffd3b4a3a389d76833f1f8113d252ed664b754cc1f66e9dedfec1a22a11e58678ceef41457741210",
          "sha256": "73da64db4ec2d73c1d8e684de7aa1839fd9d8547f8aa1742713ef3c421477751",
          "sha1": "239a16f1919d0016a8fb73cb8d3a45c79c6ca0a6",
          "md5": "32569a92d6b0e5fd5ef5ec33d52e75c7"
        }
      ]
    },
    {
      "name": "frontendRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-frontend-2.2.klib",
          "url": "graph-meta-frontend-2.2.klib",
          "size": 31045,
          "sha512": "ec1bfc65f5d52f44e34fd94e8896f58a734deeae55375184ffd3b4a3a389d76833f1f8113d252ed664b754cc1f66e9dedfec1a22a11e58678ceef41457741210",
          "sha256": "73da64db4ec2d73c1d8e684de7aa1839fd9d8547f8aa1742713ef3c421477751",
          "sha1": "239a16f1919d0016a8fb73cb8d3a45c79c6ca0a6",
          "md5": "32569a92d6b0e5fd5ef5ec33d52e75c7"
        }
      ]
    },
    {
      "name": "frontendSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lib-frontend-2.2-sources.jar",
          "url": "graph-meta-frontend-2.2-sources.jar",
          "size": 5768,
          "sha512": "911ac6d2a2cd8563f351848f9b83f76ad950c9c0ad5fc773559bf28c68f982caaabb52325d97d30398c0d4fee77ef90d73c68c161d3d79023e19b237b07dbb67",
          "sha256": "f80df889f5bd9ece1dded6b5363fc92586b7c6956820b61f6c5235a4d30374a9",
          "sha1": "3577b3e3063106201af8ec9dd427dd33f6b8aeb8",
          "md5": "77f87fbb501043f703045a62ac7ebd0e"
        }
      ]
    }
  ]
}
