{
  "formatVersion": "1.1",
  "component": {
    "url": "../../graph-meta/2.1/graph-meta-2.1.module",
    "group": "ru.landgrafhomyak.itmo.web",
    "module": "graph-meta",
    "version": "2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "frontendApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-frontend-2.1.klib",
          "url": "graph-meta-frontend-2.1.klib",
          "size": 31043,
          "sha512": "97b3fbee5150faee38c69c19da53298458e92401b0a03a3bdea51d4fb7c6e81764a2ddea14bd817b6aae6c08370cd7bf8302743e1d071d39485b76bf3b9496a3",
          "sha256": "aa2c321d375c26dd3e9618aea3490eb0ed62ba9dfa415718aa0ab4243c0df08e",
          "sha1": "c001f6429d359114ff64a99860ee90f486a1018f",
          "md5": "3e68d0c125a398830e950ef1755d13bf"
        }
      ]
    },
    {
      "name": "frontendRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-frontend-2.1.klib",
          "url": "graph-meta-frontend-2.1.klib",
          "size": 31043,
          "sha512": "97b3fbee5150faee38c69c19da53298458e92401b0a03a3bdea51d4fb7c6e81764a2ddea14bd817b6aae6c08370cd7bf8302743e1d071d39485b76bf3b9496a3",
          "sha256": "aa2c321d375c26dd3e9618aea3490eb0ed62ba9dfa415718aa0ab4243c0df08e",
          "sha1": "c001f6429d359114ff64a99860ee90f486a1018f",
          "md5": "3e68d0c125a398830e950ef1755d13bf"
        }
      ]
    },
    {
      "name": "frontendSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lib-frontend-2.1-sources.jar",
          "url": "graph-meta-frontend-2.1-sources.jar",
          "size": 5763,
          "sha512": "e123ba3575c037459fd680e5c546aa419c44a4e251302d94abc16a1c73073b44bfc26bc1e0a277e44f50526d52209bc7ed48c66d7e49727688980ce99cd1f208",
          "sha256": "6536c96d00b7f5f8e432bd996c9433767f8fc44edb1bd4e877b5aaa6e9441f31",
          "sha1": "79214691d8905788ef89265d706f2cc0f1fddb86",
          "md5": "20d924b796d87e9cdc35ec5316aed81a"
        }
      ]
    }
  ]
}
