{
  "formatVersion": "1.1",
  "component": {
    "url": "../../graph-meta/2.0/graph-meta-2.0.module",
    "group": "ru.landgrafhomyak.itmo.web",
    "module": "graph-meta",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "backendApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-backend-2.0.jar",
          "url": "graph-meta-backend-2.0.jar",
          "size": 28636,
          "sha512": "bff7328f4b45102c24f6bc4ca2a259048709cb2133cd4028ea8c14ced37c1c4d3a3f53574fd62e1a280bf8699769d22f82a55836d2e996bc3fcb2d8058fed23b",
          "sha256": "0cdb304abedf839731cb210a60ad780aede5e2e40ec9b225e56822a996d83948",
          "sha1": "4456b82b42c4ecfb09cc326f53577db2df7ef7dc",
          "md5": "dd51c67e386317babbeddfc9c69755b2"
        }
      ]
    },
    {
      "name": "backendRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-backend-2.0.jar",
          "url": "graph-meta-backend-2.0.jar",
          "size": 28636,
          "sha512": "bff7328f4b45102c24f6bc4ca2a259048709cb2133cd4028ea8c14ced37c1c4d3a3f53574fd62e1a280bf8699769d22f82a55836d2e996bc3fcb2d8058fed23b",
          "sha256": "0cdb304abedf839731cb210a60ad780aede5e2e40ec9b225e56822a996d83948",
          "sha1": "4456b82b42c4ecfb09cc326f53577db2df7ef7dc",
          "md5": "dd51c67e386317babbeddfc9c69755b2"
        }
      ]
    },
    {
      "name": "backendSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lib-backend-2.0-sources.jar",
          "url": "graph-meta-backend-2.0-sources.jar",
          "size": 5761,
          "sha512": "5c9831d2f37a82f78fbca0918cf493948619106116186ff8cb1adf9b2072ded1b3fdcaa33ef48ab7f44682c4a4d089487aea7c32debbaf68df15519cdb893a57",
          "sha256": "f8867d816e9afbb7eb2adf94c8e77a2cb681ca25cb0f06c5c932faf1b106c5db",
          "sha1": "6642712175484bdc64a7910c96f4a7715316b906",
          "md5": "c2a4606223e4550a36fb0e44cea40499"
        }
      ]
    }
  ]
}
