{
  "formatVersion": "1.1",
  "component": {
    "url": "../../graph-meta/2.2/graph-meta-2.2.module",
    "group": "ru.landgrafhomyak.itmo.web",
    "module": "graph-meta",
    "version": "2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "backendApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-backend-2.2.jar",
          "url": "graph-meta-backend-2.2.jar",
          "size": 28312,
          "sha512": "d6f170c0334deb70bc693d9481e973745949246bcae33c4e1a39c67a5261fcc482271ffdf8c64d6414953793dbc3a57cb961e58638d63f9d3c187df90cbe1d8a",
          "sha256": "ba02ff2fd2c532f331eeb1152939d8948c4169078a5926b6d355307b7913fec1",
          "sha1": "e489dd6b5a0313bfcc5834b0999b0c59a4021838",
          "md5": "63cc5273b4cf344fc66dd7106f8f71d8"
        }
      ]
    },
    {
      "name": "backendRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-backend-2.2.jar",
          "url": "graph-meta-backend-2.2.jar",
          "size": 28312,
          "sha512": "d6f170c0334deb70bc693d9481e973745949246bcae33c4e1a39c67a5261fcc482271ffdf8c64d6414953793dbc3a57cb961e58638d63f9d3c187df90cbe1d8a",
          "sha256": "ba02ff2fd2c532f331eeb1152939d8948c4169078a5926b6d355307b7913fec1",
          "sha1": "e489dd6b5a0313bfcc5834b0999b0c59a4021838",
          "md5": "63cc5273b4cf344fc66dd7106f8f71d8"
        }
      ]
    },
    {
      "name": "backendSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lib-backend-2.2-sources.jar",
          "url": "graph-meta-backend-2.2-sources.jar",
          "size": 5768,
          "sha512": "911ac6d2a2cd8563f351848f9b83f76ad950c9c0ad5fc773559bf28c68f982caaabb52325d97d30398c0d4fee77ef90d73c68c161d3d79023e19b237b07dbb67",
          "sha256": "f80df889f5bd9ece1dded6b5363fc92586b7c6956820b61f6c5235a4d30374a9",
          "sha1": "3577b3e3063106201af8ec9dd427dd33f6b8aeb8",
          "md5": "77f87fbb501043f703045a62ac7ebd0e"
        }
      ]
    }
  ]
}
