{
  "formatVersion": "1.1",
  "component": {
    "url": "../../graph-meta/2.1/graph-meta-2.1.module",
    "group": "ru.landgrafhomyak.itmo.web",
    "module": "graph-meta",
    "version": "2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "backendApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-backend-2.1.jar",
          "url": "graph-meta-backend-2.1.jar",
          "size": 28305,
          "sha512": "d881a6be0d0161ab67c043889b05050a1b135b2f4e9f4358b0f689371085292bb7bf0bbd8f316e27ff5d62ff3dcac8b55bf50a1e82c57daf98c51aef3e209f9f",
          "sha256": "c7ae7cefd294b5b9b1ea5b8efc7aa6d18c377c5886410b2e5484922e46fa5691",
          "sha1": "86ddf2e4b33f1f81d9fd0d1f36470c86eccb70f7",
          "md5": "b56a3b1d9a127f92ae0d7dbe44e61234"
        }
      ]
    },
    {
      "name": "backendRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-backend-2.1.jar",
          "url": "graph-meta-backend-2.1.jar",
          "size": 28305,
          "sha512": "d881a6be0d0161ab67c043889b05050a1b135b2f4e9f4358b0f689371085292bb7bf0bbd8f316e27ff5d62ff3dcac8b55bf50a1e82c57daf98c51aef3e209f9f",
          "sha256": "c7ae7cefd294b5b9b1ea5b8efc7aa6d18c377c5886410b2e5484922e46fa5691",
          "sha1": "86ddf2e4b33f1f81d9fd0d1f36470c86eccb70f7",
          "md5": "b56a3b1d9a127f92ae0d7dbe44e61234"
        }
      ]
    },
    {
      "name": "backendSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lib-backend-2.1-sources.jar",
          "url": "graph-meta-backend-2.1-sources.jar",
          "size": 5763,
          "sha512": "e123ba3575c037459fd680e5c546aa419c44a4e251302d94abc16a1c73073b44bfc26bc1e0a277e44f50526d52209bc7ed48c66d7e49727688980ce99cd1f208",
          "sha256": "6536c96d00b7f5f8e432bd996c9433767f8fc44edb1bd4e877b5aaa6e9441f31",
          "sha1": "79214691d8905788ef89265d706f2cc0f1fddb86",
          "md5": "20d924b796d87e9cdc35ec5316aed81a"
        }
      ]
    }
  ]
}
