{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.landgrafhomyak.itmo.web",
    "module": "graph-meta",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-metadata-1.0.jar",
          "url": "graph-meta-1.0.jar",
          "size": 6413,
          "sha512": "9050beea1b632591d0cb78cb026aae349ce9453e34d299947cd43ce962e5b15322a7e455fc67dc0c0e98b398a6b865c2534e1801de8fea37708b1e71c84f3638",
          "sha256": "44bcc0102dfc730b48232fb53f2a9a962de34c225e2c6366638555ee447fdf62",
          "sha1": "0759f2693b6de2bda4dd203ba366e35be3255099",
          "md5": "a2461171b5f14ab996bc01fc01685e17"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "lib-kotlin-1.0-sources.jar",
          "url": "graph-meta-1.0-sources.jar",
          "size": 5379,
          "sha512": "8c2d5e668a73e48528831eb04d34b51f8399ea395eef1a69275bbc18937ea8c5e1a071d089e35228b95392923cdbb8c53575c9f2f8d2dcd63d50ce7bfa0538c3",
          "sha256": "ba530206aed46085f147e654b13e81eb765878cb3ec99d970a709337e5f9c890",
          "sha1": "b24122d8fdcd5032f0b855e3c512b6c90e42f719",
          "md5": "9b9489ac2a6f14f1e420d20e740ffa10"
        }
      ]
    },
    {
      "name": "backendApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../graph-meta-backend/1.0/graph-meta-backend-1.0.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-backend",
        "version": "1.0"
      }
    },
    {
      "name": "backendRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../graph-meta-backend/1.0/graph-meta-backend-1.0.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-backend",
        "version": "1.0"
      }
    },
    {
      "name": "backendSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../graph-meta-backend/1.0/graph-meta-backend-1.0.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-backend",
        "version": "1.0"
      }
    },
    {
      "name": "frontendApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../graph-meta-frontend/1.0/graph-meta-frontend-1.0.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-frontend",
        "version": "1.0"
      }
    },
    {
      "name": "frontendRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../graph-meta-frontend/1.0/graph-meta-frontend-1.0.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-frontend",
        "version": "1.0"
      }
    },
    {
      "name": "frontendSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../graph-meta-frontend/1.0/graph-meta-frontend-1.0.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-frontend",
        "version": "1.0"
      }
    }
  ]
}
