{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.landgrafhomyak.itmo.web",
    "module": "graph-meta",
    "version": "2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-metadata-2.2.jar",
          "url": "graph-meta-2.2.jar",
          "size": 6519,
          "sha512": "0ce322fb9c1a922e6536dbe2b252ff85a2c4acc6291d9a907ea5ea86fa0d7d5daa7c9ff182935385a300f0763b8ec15192fabc1aa1de475bf5878145f825af69",
          "sha256": "5862ec3c49af3e72ae93feef835da258955e318fb7af1e7184305667be34e7c3",
          "sha1": "772d7b4bf8bbeaee538efb54c506838407cca729",
          "md5": "40baa7355208023ef2100b6cbd0eac3e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "lib-kotlin-2.2-sources.jar",
          "url": "graph-meta-2.2-sources.jar",
          "size": 5768,
          "sha512": "911ac6d2a2cd8563f351848f9b83f76ad950c9c0ad5fc773559bf28c68f982caaabb52325d97d30398c0d4fee77ef90d73c68c161d3d79023e19b237b07dbb67",
          "sha256": "f80df889f5bd9ece1dded6b5363fc92586b7c6956820b61f6c5235a4d30374a9",
          "sha1": "3577b3e3063106201af8ec9dd427dd33f6b8aeb8",
          "md5": "77f87fbb501043f703045a62ac7ebd0e"
        }
      ]
    },
    {
      "name": "backendApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../graph-meta-backend/2.2/graph-meta-backend-2.2.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-backend",
        "version": "2.2"
      }
    },
    {
      "name": "backendRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../graph-meta-backend/2.2/graph-meta-backend-2.2.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-backend",
        "version": "2.2"
      }
    },
    {
      "name": "backendSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../graph-meta-backend/2.2/graph-meta-backend-2.2.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-backend",
        "version": "2.2"
      }
    },
    {
      "name": "frontendApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../graph-meta-frontend/2.2/graph-meta-frontend-2.2.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-frontend",
        "version": "2.2"
      }
    },
    {
      "name": "frontendRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../graph-meta-frontend/2.2/graph-meta-frontend-2.2.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-frontend",
        "version": "2.2"
      }
    },
    {
      "name": "frontendSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../graph-meta-frontend/2.2/graph-meta-frontend-2.2.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-frontend",
        "version": "2.2"
      }
    }
  ]
}
