{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.landgrafhomyak.itmo.web",
    "module": "graph-meta",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-metadata-2.0.jar",
          "url": "graph-meta-2.0.jar",
          "size": 6517,
          "sha512": "77b4d8c729d4d4a46a9316e8b7d1e01e58440401156337eb8a43d374792685c21a1b8579617b35e2d6a57e8f675149b08543f1e68f00a05122a5565a7ecf4d2c",
          "sha256": "559add8446f3509beb0ae12f1a72aca0c606a9c611b20986f3554bb615273115",
          "sha1": "85cb6ef4439f2ffca7db1274f82c31cec7d86f72",
          "md5": "794a22554cb6cd09ec4d5f5a4eb7cb5a"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "lib-kotlin-2.0-sources.jar",
          "url": "graph-meta-2.0-sources.jar",
          "size": 5761,
          "sha512": "5c9831d2f37a82f78fbca0918cf493948619106116186ff8cb1adf9b2072ded1b3fdcaa33ef48ab7f44682c4a4d089487aea7c32debbaf68df15519cdb893a57",
          "sha256": "f8867d816e9afbb7eb2adf94c8e77a2cb681ca25cb0f06c5c932faf1b106c5db",
          "sha1": "6642712175484bdc64a7910c96f4a7715316b906",
          "md5": "c2a4606223e4550a36fb0e44cea40499"
        }
      ]
    },
    {
      "name": "backendApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../graph-meta-backend/2.0/graph-meta-backend-2.0.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-backend",
        "version": "2.0"
      }
    },
    {
      "name": "backendRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../graph-meta-backend/2.0/graph-meta-backend-2.0.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-backend",
        "version": "2.0"
      }
    },
    {
      "name": "backendSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../graph-meta-backend/2.0/graph-meta-backend-2.0.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-backend",
        "version": "2.0"
      }
    },
    {
      "name": "frontendApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../graph-meta-frontend/2.0/graph-meta-frontend-2.0.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-frontend",
        "version": "2.0"
      }
    },
    {
      "name": "frontendRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../graph-meta-frontend/2.0/graph-meta-frontend-2.0.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-frontend",
        "version": "2.0"
      }
    },
    {
      "name": "frontendSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../graph-meta-frontend/2.0/graph-meta-frontend-2.0.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-frontend",
        "version": "2.0"
      }
    }
  ]
}
