{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.landgrafhomyak.itmo.web",
    "module": "graph-meta",
    "version": "2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-metadata-2.1.jar",
          "url": "graph-meta-2.1.jar",
          "size": 6519,
          "sha512": "0ce322fb9c1a922e6536dbe2b252ff85a2c4acc6291d9a907ea5ea86fa0d7d5daa7c9ff182935385a300f0763b8ec15192fabc1aa1de475bf5878145f825af69",
          "sha256": "5862ec3c49af3e72ae93feef835da258955e318fb7af1e7184305667be34e7c3",
          "sha1": "772d7b4bf8bbeaee538efb54c506838407cca729",
          "md5": "40baa7355208023ef2100b6cbd0eac3e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "lib-kotlin-2.1-sources.jar",
          "url": "graph-meta-2.1-sources.jar",
          "size": 5763,
          "sha512": "e123ba3575c037459fd680e5c546aa419c44a4e251302d94abc16a1c73073b44bfc26bc1e0a277e44f50526d52209bc7ed48c66d7e49727688980ce99cd1f208",
          "sha256": "6536c96d00b7f5f8e432bd996c9433767f8fc44edb1bd4e877b5aaa6e9441f31",
          "sha1": "79214691d8905788ef89265d706f2cc0f1fddb86",
          "md5": "20d924b796d87e9cdc35ec5316aed81a"
        }
      ]
    },
    {
      "name": "backendApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../graph-meta-backend/2.1/graph-meta-backend-2.1.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-backend",
        "version": "2.1"
      }
    },
    {
      "name": "backendRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../graph-meta-backend/2.1/graph-meta-backend-2.1.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-backend",
        "version": "2.1"
      }
    },
    {
      "name": "backendSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../graph-meta-backend/2.1/graph-meta-backend-2.1.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-backend",
        "version": "2.1"
      }
    },
    {
      "name": "frontendApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../graph-meta-frontend/2.1/graph-meta-frontend-2.1.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-frontend",
        "version": "2.1"
      }
    },
    {
      "name": "frontendRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../graph-meta-frontend/2.1/graph-meta-frontend-2.1.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-frontend",
        "version": "2.1"
      }
    },
    {
      "name": "frontendSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../graph-meta-frontend/2.1/graph-meta-frontend-2.1.module",
        "group": "ru.landgrafhomyak.itmo.web",
        "module": "graph-meta-frontend",
        "version": "2.1"
      }
    }
  ]
}
